/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface2.h"

void *enviarnotificacion_1_svc(int *argp, struct svc_req *rqstp) {
  static char *result;

  /*
   * insert server code here
   */

  printf("Desde enviarnotificacion()...\n");
  printf("Notificación recibida: %d\n", *argp);
  printf("Saliendo de enviarnotificacion()...\n\n");

  return (void *)&result;
}
